#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

m4 system/blockMeshDict.m4 > system/blockMeshDict

runApplication blockMesh

runApplication setFields

runApplication decomposePar

python3 standingTank_script.py 
# mpirun --allow-run-as-root -n 2 python3 standingTank_script.py
#------------------------------------------------------------------------------
